version: 1
formatters:
  simple_fmt:
    format: '%(message)s'
  detail_fmt:
    format: '%(asctime)s %(levelname)s %(filename)s:%(lineno)d %(funcName)s() %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    formatter: simple_fmt
    stream: ext://sys.stdout
  file:
    class: logging.handlers.RotatingFileHandler
 #   class: logging.StreamHandler
    formatter: detail_fmt
    filename: logs/nrm.log
    maxBytes: 10485760
    backupCount: 10
    encoding: "utf-8"
    mode: "a"
root:
  level: INFO
  #handlers: [file]
  handlers: [file,console]
disable_existing_loggers: False


